In [1]:
# ------------------------------------------------------------
# STEP 1: LOAD DATA
# ------------------------------------------------------------

import pandas as pd
import numpy as np

url = "gs://agntworks-data-dev/wheelsup/raw/wingx/WingX_2026.zip"

df = pd.read_csv(url)

print("Shape:", df.shape)
df.head()

/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.cloud.storage_control_v2 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.storage_control_v2 past that date.
  warnings.warn(message, FutureWarning)

Shape: (885823, 18)

,FlightDate_utc,ArrivalDate_utc,Operator,FromAirport,FromCity,FromState,ToAirport,ToCity,ToState,Hours,aircraft_tailsign,aircraft_tailsign_certification,operator_type,aircraft_icao_code,aircraft_type,aircraft_model,aircraft_segment,fuel_uplift_usg
0,2026-03-31T07:44:00.000Z,2026-03-31T09:20:00.000Z,ProAir Aviation GmbH,LSGG,Geneva,NaN,LHBP,Budapest,NaN,1.600000,DCLIK,Commercial/ CAT / Part 135,Aircraft Management,C25C,Cessna-Citation CJ4,Citation CJ4 Gen2,Light Jet,307.20
1,2026-03-31T20:45:00.000Z,2026-03-31T22:01:00.000Z,CMH Services Aviation Inc,KORL,Orlando,FL,KTYS,Knoxville,TN,1.266667,N74CH,Part 91 / Non Commercial,Private Flight Department,E550,Embraer-Legacy 500 / Praetor 600,Praetor 600,Super Midsize Jet,393.93
2,2026-03-31T14:27:52.000Z,2026-03-31T15:52:44.000Z,Deer Jet,ZSFZ,Fuzhou,35,ZGSZ,Shenzhen,44,1.414444,B8302,Part 91 / Non Commercial,Aircraft Management,GLF5,Gulfstream-GV/500/550,G550,Ultra Long Range Jet,603.97
3,2026-03-31T22:12:30.000Z,2026-04-01T00:13:38.000Z,Beacon Capital Partners LLC,MMSD,Los Cabos,BCS,KSBD,San Bernardino,CA,2.018889,N119AF,Part 91 / Non Commercial,Corporate Flight Department,GLF4,Gulfstream G300/350/400/450,GIV-SP,Heavy Jet,969.07
4,2026-03-31T13:31:00.000Z,2026-03-31T14:13:00.000Z,NetJets,KDAL,Dallas,TX,KDWH,Houston,TX,0.700000,N271QS,Part 91K / Fractional Ownership,Fractional Ownership,E545,Embraer-Legacy 450 / Praetor 500,Praetor 500,Midsize Jet,210.00

In [2]:
# 1. Check for Missing Values (Nulls)
null_counts = df.isnull().sum()

# 2. Check for Unique Values (Cardinality)
unique_counts = df.nunique()

# 3. Calculate the % of uniqueness (Ratio)
# If this ratio is very low (e.g. < 5%), it's a great candidate for 'category'
unique_ratio = (df.nunique() / len(df)) * 100

# Combine into a summary table
eda_summary = pd.DataFrame({
    'Null Values': null_counts,
    'Unique Values': unique_counts,
    'Uniqueness Ratio (%)': unique_ratio.round(4)
})

print(eda_summary)

                                 Null Values  Unique Values  \
FlightDate_utc                             0         260602
ArrivalDate_utc                            0         263201
Operator                                   0          14560
FromAirport                                0           6761
FromCity                               11402           4300
FromState                             171350            294
ToAirport                                  0           7181
ToCity                                 11721           4390
ToState                               171007            297
Hours                                      0          21898
aircraft_tailsign                          0          22053
aircraft_tailsign_certification            0              3
operator_type                              0              6
aircraft_icao_code                         0            108
aircraft_type                              0            103
aircraft_model                             0            315
aircraft_segment                           0              9
fuel_uplift_usg                            0          82184

                                 Uniqueness Ratio (%)
FlightDate_utc                                29.4192
ArrivalDate_utc                               29.7126
Operator                                       1.6437
FromAirport                                    0.7632
FromCity                                       0.4854
FromState                                      0.0332
ToAirport                                      0.8107
ToCity                                         0.4956
ToState                                        0.0335
Hours                                          2.4721
aircraft_tailsign                              2.4895
aircraft_tailsign_certification                0.0003
operator_type                                  0.0007
aircraft_icao_code                             0.0122
aircraft_type                                  0.0116
aircraft_model                                 0.0356
aircraft_segment                               0.0010
fuel_uplift_usg                                9.2777

In [3]:
# 'K' is the prefix for the Continental USA. 
# Anything else (C=Canada, L=Europe, M=Mexico) is International.
non_us_prefixes = df[df['ToState'].isnull()]['ToAirport'].str[0].value_counts()
print("Top 10 Airport Prefixes for Missing States:")
print(non_us_prefixes.head(10))

Top 10 Airport Prefixes for Missing States:
ToAirport
L    68437
E    38781
M    15469
T     9446
S     8957
K     5960
O     4287
R     4188
V     4143
G     2703
Name: count, dtype: int64

In [4]:
# 1. Filter for FromAirport starting with 'K' AND FromState being Null
k_null_from = df[(df['FromAirport'].str.startswith('K')) & (df['FromState'].isna())]

# 2. Get the top 10 most frequent mystery airports
top_10_k_nulls = k_null_from['FromAirport'].value_counts().head(10)

print("Top 10 US Airports (K-prefix) with missing State/City data:")
print(top_10_k_nulls)

Top 10 US Airports (K-prefix) with missing State/City data:
FromAirport
KF45    403
KT82    346
KX60    183
K27K    179
K11R    138
KF82    116
KX04    102
KM19    102
K1R8     90
K0A9     88
Name: count, dtype: int64

In [5]:
import pandas as pd

# 1. First, handle the Nulls so they are labeled correctly in the lookup
df['FromState'] = df['FromState'].fillna('International/Unknown')
df['ToState'] = df['ToState'].fillna('International/Unknown')
df['FromCity'] = df['FromCity'].fillna('Unknown')
df['ToCity'] = df['ToCity'].fillna('Unknown')

# 2. Convert Dates (This turns strings into math-friendly objects)
df['FlightDate_utc'] = pd.to_datetime(df['FlightDate_utc'])
df['ArrivalDate_utc'] = pd.to_datetime(df['ArrivalDate_utc'])

# 3. Apply the Category Mapping (The "Lookup" Magic)
# These are the columns where we replace bulk text with short reference codes
cat_columns = [
    'Operator', 'FromAirport', 'FromCity', 'FromState', 
    'ToAirport', 'ToCity', 'ToState', 'aircraft_tailsign',
    'aircraft_tailsign_certification', 'operator_type', 
    'aircraft_icao_code', 'aircraft_type', 'aircraft_model', 'aircraft_segment'
]

for col in cat_columns:
    df[col] = df[col].astype('category')

# 4. Downcast numbers (Saves 50% space on these columns)
df['Hours'] = pd.to_numeric(df['Hours'], downcast='float')
df['fuel_uplift_usg'] = pd.to_numeric(df['fuel_uplift_usg'], downcast='float')

# 5. The Moment of Truth: Check how much memory you saved
print(df.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885823 entries, 0 to 885822
Data columns (total 18 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   FlightDate_utc                   885823 non-null  datetime64[ns, UTC]
 1   ArrivalDate_utc                  885823 non-null  datetime64[ns, UTC]
 2   Operator                         885823 non-null  category
 3   FromAirport                      885823 non-null  category
 4   FromCity                         885823 non-null  category
 5   FromState                        885823 non-null  category
 6   ToAirport                        885823 non-null  category
 7   ToCity                           885823 non-null  category
 8   ToState                          885823 non-null  category
 9   Hours                            885823 non-null  float32
 10  aircraft_tailsign                885823 non-null  category
 11  aircraft_tailsign_certification  885823 non-null  category
 12  operator_type                    885823 non-null  category
 13  aircraft_icao_code               885823 non-null  category
 14  aircraft_type                    885823 non-null  category
 15  aircraft_model                   885823 non-null  category
 16  aircraft_segment                 885823 non-null  category
 17  fuel_uplift_usg                  885823 non-null  float64
dtypes: category(14), datetime64[ns, UTC](2), float32(1), float64(1)
memory usage: 48.7 MB
None

In [6]:
# Returns an array of unique names
print(df['Operator'].unique())

['ProAir Aviation GmbH', 'CMH Services Aviation Inc', 'Deer Jet', 'Beacon Capital Partners LLC', 'NetJets', ..., 'MEXICAN NAVY-Operator', 'Jaco Oil Company', 'Falcon 399 LLC', 'High Tec Industries Services Inc', 'Pack Force One LLC']
Length: 14560
Categories (14560, object): ['01052-Operator', '01949-Operator', '0262 Aviation Inc Trustee', '04-Operator', ..., 'flyNEAT', 'iXAir', 'mLeasing SP zoo', 'nextair LLC']

In [7]:
# 1. Get flight counts for every operator
counts = df['Operator'].value_counts()

# 2. Isolate the Top 20
top_20 = counts.head(20).to_frame(name='Flight Count')

# 3. Sum up all operators from index 20 onwards
others_sum = counts.iloc[20:].sum()

# 4. Create a row for the 'Other' category
# We subtract 20 from the total length to show exactly how many operators are grouped
other_label = f"Other Operators ({len(counts) - 20:,} total)"
other_row = pd.DataFrame({'Flight Count': [others_sum]}, index=[other_label])

# 5. Combine Top 20 + Other
market_summary = pd.concat([top_20, other_row])

# 6. Calculate Market Share Percentage
total_flights = market_summary['Flight Count'].sum()
market_summary['Market Share %'] = (market_summary['Flight Count'] / total_flights * 100).round(2)

print(market_summary)

                                Flight Count  Market Share %
NetJets                               111573           12.60
Flexjet                                45233            5.11
NetJets Europe                         13520            1.53
Executive Jet Management               11094            1.25
flyExclusive                           10457            1.18
VistaJet Ltd                            8903            1.01
Vista America                           8711            0.98
Solairus Aviation                       8233            0.93
Contour Aviation                        7660            0.86
Wheels Up Private Jets                  7572            0.85
Jet Linx Aviation                       5633            0.64
Airsprint Inc                           5601            0.63
Baker Aviation LLC                      4587            0.52
Executive AirShare                      3746            0.42
Nicholas Air                            3710            0.42
Vista Germany                           3283            0.37
Planesense                              2694            0.30
Summit Aviation                         2635            0.30
Aerolineas Ejecutivas SA                2585            0.29
Northern Jet Management Inc             2540            0.29
Other Operators (14,540 total)        615853           69.52

In [8]:
import pandas as pd

# 1. Group by Operator and get both count and the operator type
# We use 'first' for operator_type assuming one operator has one type
operator_data = df.groupby('Operator').agg(
    Flight_Count=('Operator', 'count'),
    Operator_Type=('operator_type', 'first')
).sort_values(by='Flight_Count', ascending=False)

# 2. Isolate the Top 20
top_20 = operator_data.head(20).copy()

# 3. Sum up all operators from index 20 onwards for the 'Other' row
others_sum = operator_data['Flight_Count'].iloc[20:].sum()

# 4. Create the 'Other' row
# Operator_Type for 'Other' is marked as 'N/A' or 'Various'
other_label = f"Other Operators ({len(operator_data) - 20:,} total)"
other_row = pd.DataFrame(
    {'Flight_Count': [others_sum], 'Operator_Type': ['Various']}, 
    index=[other_label]
)

# 5. Combine Top 20 + Other
market_summary = pd.concat([top_20, other_row])

# 6. Calculate Market Share Percentage
total_flights = market_summary['Flight_Count'].sum()
market_summary['Market Share %'] = (market_summary['Flight_Count'] / total_flights * 100).round(2)

# Rename column for consistency with your previous output
market_summary = market_summary.rename(columns={'Flight_Count': 'Flight Count', 'Operator_Type': 'Operator Type'})

# Reorder columns to put Operator Type in the middle
market_summary = market_summary[['Flight Count', 'Operator Type', 'Market Share %']]

print(market_summary)

                                Flight Count         Operator Type  \
NetJets                               111573  Fractional Ownership
Flexjet                                45233  Fractional Ownership
NetJets Europe                         13520  Fractional Ownership
Executive Jet Management               11094   Aircraft Management
flyExclusive                           10457       Branded Charter
VistaJet Ltd                            8903       Branded Charter
Vista America                           8711       Branded Charter
Solairus Aviation                       8233   Aircraft Management
Contour Aviation                        7660   Aircraft Management
Wheels Up Private Jets                  7572       Branded Charter
Jet Linx Aviation                       5633   Aircraft Management
Airsprint Inc                           5601  Fractional Ownership
Baker Aviation LLC                      4587   Aircraft Management
Executive AirShare                      3746  Fractional Ownership
Nicholas Air                            3710       Branded Charter
Vista Germany                           3283       Branded Charter
Planesense                              2694  Fractional Ownership
Summit Aviation                         2635   Aircraft Management
Aerolineas Ejecutivas SA                2585   Aircraft Management
Northern Jet Management Inc             2540   Aircraft Management
Other Operators (14,540 total)        615853               Various

                                Market Share %
NetJets                                  12.60
Flexjet                                   5.11
NetJets Europe                            1.53
Executive Jet Management                  1.25
flyExclusive                              1.18
VistaJet Ltd                              1.01
Vista America                             0.98
Solairus Aviation                         0.93
Contour Aviation                          0.86
Wheels Up Private Jets                    0.85
Jet Linx Aviation                         0.64
Airsprint Inc                             0.63
Baker Aviation LLC                        0.52
Executive AirShare                        0.42
Nicholas Air                              0.42
Vista Germany                             0.37
Planesense                                0.30
Summit Aviation                           0.30
Aerolineas Ejecutivas SA                  0.29
Northern Jet Management Inc               0.29
Other Operators (14,540 total)           69.52

/var/tmp/ipykernel_54433/2201172049.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  operator_data = df.groupby('Operator').agg(

In [9]:
print(f"Min Date: {df['FlightDate_utc'].min()}")
print(f"Max Date: {df['FlightDate_utc'].max()}")

Min Date: 2026-01-01 00:00:00+00:00
Max Date: 2026-03-31 23:59:45+00:00

In [10]:
# 1. The definitive Wheels Up Subsidiary List
wu_subsidiaries = [
    'Wheels Up Private Jets', 'Wheels Up LLC', 'Mountain Aviation', 
    'Alante Air Charter'
]

# 2. Create the boolean feature
df['is_wheels_up'] = df['Operator'].isin(wu_subsidiaries)

# 3. Filter for Super Midsize and group by the new feature
smj_check = df[df['aircraft_segment'] == 'Super Midsize Jet'].groupby('is_wheels_up').size()

# 4. MARKET SHARE LOGIC
# Extract the counts (using .get to avoid errors if a category is missing)
wu_smj_flights = smj_check.get(True, 0)
total_smj_flights = smj_check.sum()

# Calculate the percentage
if total_smj_flights > 0:
    smj_market_share = (wu_smj_flights / total_smj_flights) * 100
else:
    smj_market_share = 0

# 5. Final Output
print("--- Super Midsize Segment Analysis ---")
print(f"Wheels Up Flights: {wu_smj_flights:,}")
print(f"Total Market Size: {total_smj_flights:,}")
print(f"Wheels Up Market Share: {smj_market_share:.3f}%")

--- Super Midsize Segment Analysis ---
Wheels Up Flights: 2,309
Total Market Size: 204,020
Wheels Up Market Share: 1.132%

In [11]:
# 1. Filter for the specific segment
df_smj = df[df['aircraft_segment'] == 'Super Midsize Jet']

# 2. Check for the default values in geographic columns within this segment
unknown_from_state = (df_smj['FromState'] == 'International/Unknown').sum()
unknown_to_state = (df_smj['ToState'] == 'International/Unknown').sum()
unknown_from_city = (df_smj['FromCity'] == 'Unknown').sum()
unknown_to_city = (df_smj['ToCity'] == 'Unknown').sum()

print(f"--- Analysis for 'Super Midsize Jet' ({len(df_smj)} total flights) ---")
print(f"Flights from 'International/Unknown' State: {unknown_from_state}")
print(f"Flights to 'International/Unknown' State:   {unknown_to_state}")
print(f"Flights from 'Unknown' City:             {unknown_from_city}")
print(f"Flights to 'Unknown' City:               {unknown_to_city}")

# 3. Check if the segment itself has any 'Unknown' or 'Null' placeholders
print(f"\nNulls in segment column: {df['aircraft_segment'].isnull().sum()}")

--- Analysis for 'Super Midsize Jet' (204020 total flights) ---
Flights from 'International/Unknown' State: 28329
Flights to 'International/Unknown' State:   28181
Flights from 'Unknown' City:             1023
Flights to 'Unknown' City:               1051

Nulls in segment column: 0

In [12]:
import pandas as pd
import requests
from io import StringIO

# Use the permanent raw URL WITHOUT the temporary token
url = "https://raw.githubusercontent.com/agntworks-ai/agntworks-experiments/main/pricing/eda/amit/icao_cluster.csv"
token = "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"

headers = {'Authorization': f'token {token}'}
response = requests.get(url, headers=headers)

if response.status_code == 200:
    df_cluster = pd.read_csv(StringIO(response.text))
    print("Shape:", df_cluster.shape)
    display(df_cluster.head())
else:
    print(f"Failed to fetch data: {response.status_code}")

Shape: (38851, 2)

   icao          cluster
0  00AA   DENVER_CLUSTER
1  00AK    OTHER_CLUSTER
2  00AL  ATLANTA_CLUSTER
3  00AN    OTHER_CLUSTER
4  00AS   DALLAS_CLUSTER

In [13]:
# 1. Create the lookup dictionary using the correct column names
# Swapping 'ident' for 'icao' and 'Cluster' for 'cluster' based on your snippet
cluster_map = dict(zip(df_cluster['icao'], df_cluster['cluster']))

# 2. Map the individual clusters to your main flight 'df'
df['from_cluster'] = df['FromAirport'].map(cluster_map).fillna('Other')
df['to_cluster'] = df['ToAirport'].map(cluster_map).fillna('Other')

# 3. Create the concatenated corridor feature
df['From_To_Cluster'] = df['from_cluster'].astype(str) + ' - ' + df['to_cluster'].astype(str)

# 4. Keep that memory low! 
for col in ['from_cluster', 'to_cluster', 'From_To_Cluster']:
    df[col] = df[col].astype('category')

# 5. Verify the fix
print(df[['FromAirport', 'ToAirport', 'From_To_Cluster']].head())

  FromAirport ToAirport                     From_To_Cluster
0        LSGG      LHBP       MILAN_CLUSTER - OTHER_CLUSTER
1        KORL      KTYS   ORLANDO_CLUSTER - ATLANTA_CLUSTER
2        ZSFZ      ZGSZ       OTHER_CLUSTER - OTHER_CLUSTER
3        MMSD      KSBD  CABO_CLUSTER - LOS_ANGELES_CLUSTER
4        KDAL      KDWH    DALLAS_CLUSTER - HOUSTON_CLUSTER

In [14]:
# 1. Define your logical conditions
is_short_hop = df['Hours'] <= 0.5
is_hub_shuffle = (df['from_cluster'] == df['to_cluster']) & \
                 (df['from_cluster'] != 'Other') & \
                 (df['Hours'] <= 1.0)

# 2. Create the feature: 'Y' for Reposition, 'N' for Revenue
# We use np.where for a fast, vectorized assignment
import numpy as np
df['reposition_flight'] = np.where(is_short_hop | is_hub_shuffle, 'Y', 'N')

# 3. Quick Vibe Check: See the breakdown
print("Repositioning Feature Breakdown:")
print(df['reposition_flight'].value_counts())

# 4. Verification: Average duration for each category
print("\nMean Flight Duration by Category:")
print(df.groupby('reposition_flight')['Hours'].mean())

Repositioning Feature Breakdown:
reposition_flight
N    674780
Y    211043
Name: count, dtype: int64

Mean Flight Duration by Category:
reposition_flight
N    2.078139
Y    0.543304
Name: Hours, dtype: float32

In [15]:
# 1. Ensure Jupyter shows all columns without truncating them
import pandas as pd
pd.set_option('display.max_columns', None)

# 2. Show the first 5 rows with the new 'is_wheels_up' and 'reposition_flight' columns
df.head(5)

,FlightDate_utc,ArrivalDate_utc,Operator,FromAirport,FromCity,FromState,ToAirport,ToCity,ToState,Hours,aircraft_tailsign,aircraft_tailsign_certification,operator_type,aircraft_icao_code,aircraft_type,aircraft_model,aircraft_segment,fuel_uplift_usg,is_wheels_up,from_cluster,to_cluster,From_To_Cluster,reposition_flight
0,2026-03-31 07:44:00+00:00,2026-03-31 09:20:00+00:00,ProAir Aviation GmbH,LSGG,Geneva,International/Unknown,LHBP,Budapest,International/Unknown,1.600000,DCLIK,Commercial/ CAT / Part 135,Aircraft Management,C25C,Cessna-Citation CJ4,Citation CJ4 Gen2,Light Jet,307.20,False,MILAN_CLUSTER,OTHER_CLUSTER,MILAN_CLUSTER - OTHER_CLUSTER,N
1,2026-03-31 20:45:00+00:00,2026-03-31 22:01:00+00:00,CMH Services Aviation Inc,KORL,Orlando,FL,KTYS,Knoxville,TN,1.266667,N74CH,Part 91 / Non Commercial,Private Flight Department,E550,Embraer-Legacy 500 / Praetor 600,Praetor 600,Super Midsize Jet,393.93,False,ORLANDO_CLUSTER,ATLANTA_CLUSTER,ORLANDO_CLUSTER - ATLANTA_CLUSTER,N
2,2026-03-31 14:27:52+00:00,2026-03-31 15:52:44+00:00,Deer Jet,ZSFZ,Fuzhou,35,ZGSZ,Shenzhen,44,1.414444,B8302,Part 91 / Non Commercial,Aircraft Management,GLF5,Gulfstream-GV/500/550,G550,Ultra Long Range Jet,603.97,False,OTHER_CLUSTER,OTHER_CLUSTER,OTHER_CLUSTER - OTHER_CLUSTER,N
3,2026-03-31 22:12:30+00:00,2026-04-01 00:13:38+00:00,Beacon Capital Partners LLC,MMSD,Los Cabos,BCS,KSBD,San Bernardino,CA,2.018889,N119AF,Part 91 / Non Commercial,Corporate Flight Department,GLF4,Gulfstream G300/350/400/450,GIV-SP,Heavy Jet,969.07,False,CABO_CLUSTER,LOS_ANGELES_CLUSTER,CABO_CLUSTER - LOS_ANGELES_CLUSTER,N
4,2026-03-31 13:31:00+00:00,2026-03-31 14:13:00+00:00,NetJets,KDAL,Dallas,TX,KDWH,Houston,TX,0.700000,N271QS,Part 91K / Fractional Ownership,Fractional Ownership,E545,Embraer-Legacy 450 / Praetor 500,Praetor 500,Midsize Jet,210.00,False,DALLAS_CLUSTER,HOUSTON_CLUSTER,DALLAS_CLUSTER - HOUSTON_CLUSTER,N

In [16]:
# One-liner to get non-zero revenue counts by model
df[(df['reposition_flight'] == 'N') & (df['is_wheels_up'])].groupby('aircraft_model').size().sort_values(ascending=False).loc[lambda x: x > 0]

/var/tmp/ipykernel_54433/2028735953.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[(df['reposition_flight'] == 'N') & (df['is_wheels_up'])].groupby('aircraft_model').size().sort_values(ascending=False).loc[lambda x: x > 0]

aircraft_model
Phenom 300            1823
Citation X            1121
Hawker 400XP          1048
no model available     880
Citation CJ3           714
Challenger 300         636
400-XP                 398
Citation CJ3+          383
Citation CJ4           104
GIV-SP                 103
G550                    89
GVII-G600               82
Phenom 300-E            79
Citation XLS+           44
G450                    40
GVII-G500               34
Falcon 900EX-EASy       28
Citation Excel          24
Learjet 60              22
Vision SF50-G2+         20
Citation Sovereign      12
Citation M2              6
Citation XLS             1
dtype: int64

In [17]:
import pandas as pd
import numpy as np

# Ensure dates are datetime objects for calculation
df['FlightDate_utc'] = pd.to_datetime(df['FlightDate_utc'])
df['ArrivalDate_utc'] = pd.to_datetime(df['ArrivalDate_utc'])

# Calculate duration in hours
df['temp_duration'] = (df['ArrivalDate_utc'] - df['FlightDate_utc']).dt.total_seconds() / 3600

# --- PART 1: INTRA-CLUSTER (Same Cluster, not 'Other') ---
intra_cluster_mask = (df['is_wheels_up'] == True) & \
                     (df['from_cluster'] == df['to_cluster']) & \
                     (df['from_cluster'] != 'Other')

# --- PART 2: INTER-CLUSTER SHORT HOPS (Different Clusters or 'Other') ---
# Logic: Origin and Destination are NOT the same AND duration <= 30 mins
inter_cluster_short_mask = (df['is_wheels_up'] == True) & \
                           (df['from_cluster'] != df['to_cluster']) & \
                           (df['temp_duration'] <= 0.5)

# 3. Create bins for the Intra-Cluster distribution
bins = [0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
labels = ['0-0.5h', '0.5-1h', '1-1.5h', '1.5-2h', '2-2.5h', '2.5-3h', '3-3.5h', '3.5-4h', '4-4.5h', '4.5-5h']

# 4. Execute Counts
intra_dist = pd.cut(df[intra_cluster_mask]['temp_duration'], bins=bins, labels=labels).value_counts().sort_index()
inter_short_count = inter_cluster_short_mask.sum()

print("--- Q1 2026 WASTE ANALYSIS (Wheels Up Entities) ---")
print("\n1. Intra-Cluster Distribution (Same Hub):")
print(intra_dist)

print(f"\n2. Inter-Cluster Short Hops (Across Hubs <= 30m): {inter_short_count}")

# 5. Total Waste Calculation
total_intra_waste = intra_dist['0-0.5h'] + intra_dist['0.5-1h']
print(f"\nTotal Identified Waste Flights (Intra < 1h + Inter <= 30m): {total_intra_waste + inter_short_count}")

# Clean up
df.drop(columns=['temp_duration'], inplace=True)

--- Q1 2026 WASTE ANALYSIS (Wheels Up Entities) ---

1. Intra-Cluster Distribution (Same Hub):
temp_duration
0-0.5h    701
0.5-1h    721
1-1.5h    120
1.5-2h     12
2-2.5h      3
2.5-3h     16
3-3.5h      7
3.5-4h      0
4-4.5h      1
4.5-5h      0
Name: count, dtype: int64

2. Inter-Cluster Short Hops (Across Hubs <= 30m): 146

Total Identified Waste Flights (Intra < 1h + Inter <= 30m): 1568

In [18]:
# 1. Filter for Wheels Up entities
wu_df = df[df['is_wheels_up'] == True]

# 2. Calculate Counts
counts = wu_df['aircraft_segment'].value_counts()

# 3. Calculate Percentages
percentages = (wu_df['aircraft_segment'].value_counts(normalize=True) * 100)

# 4. Combine into a clean Summary Table
segment_summary = pd.DataFrame({
    'Flight Count': counts,
    'Percentage (%)': percentages
})

# 5. Sort by Percentage (Highest first)
segment_summary = segment_summary.sort_values(by='Percentage (%)', ascending=False)

print("--- Wheels Up Segment Composition (Q1 2026) ---")
print(segment_summary.round(2)) # Rounding to 2 decimal places for a clean look

--- Wheels Up Segment Composition (Q1 2026) ---
                        Flight Count  Percentage (%)
aircraft_segment
Light Jet                       6300           68.04
Super Midsize Jet               2309           24.94
Heavy Jet                        263            2.84
Ultra Long Range Jet             231            2.49
Super Light Jet                  104            1.12
Midsize Jet                       31            0.33
Very Light Jet                    20            0.22
Entry Level Jet                    1            0.01
Airliner/Bizliner(Jet)             0            0.00

In [19]:
# 1. Filter for Wheels Up and Repositioning Flights
repro_df = df[(df['is_wheels_up'] == True) & (df['reposition_flight'] == 'Y')]

# 2. Group by segment to see where the waste is concentrated
repro_counts = repro_df['aircraft_segment'].value_counts()

# 3. Calculate the percentage of total repositioning flights each segment represents
repro_pct = (repro_df['aircraft_segment'].value_counts(normalize=True) * 100)

# 4. Combine into a summary table
repro_summary = pd.DataFrame({
    'Repositioning Flights': repro_counts,
    'Share of Total Waste (%)': repro_pct
})

print("--- Wheels Up Repositioning Flights by Segment (Q1 2026) ---")
print(repro_summary.round(2))

--- Wheels Up Repositioning Flights by Segment (Q1 2026) ---
                        Repositioning Flights  Share of Total Waste (%)
aircraft_segment
Light Jet                                1108                     70.66
Super Midsize Jet                         302                     19.26
Heavy Jet                                  88                      5.61
Super Light Jet                            35                      2.23
Ultra Long Range Jet                       26                      1.66
Midsize Jet                                 9                      0.57
Airliner/Bizliner(Jet)                      0                      0.00
Entry Level Jet                             0                      0.00
Very Light Jet                              0                      0.00

In [20]:
# 1. Filter for Wheels Up and remove rows where model is missing/null
wu_clean = df[(df['is_wheels_up'] == True) & (df['aircraft_model'].notna())]
wu_clean = wu_clean[wu_clean['aircraft_model'] != 'no model available']

# 2. Pivot to get Revenue (N) and Repositioning (Y) counts
model_waste = wu_clean.groupby(['aircraft_model', 'reposition_flight']).size().unstack(fill_value=0)

# 3. Rename for clarity
model_waste.columns = ['Revenue_Flights', 'Repositioning_Flights']

# 4. Filter out models that have 0 Revenue flights (removes idle/retired fleet)
model_waste = model_waste[model_waste['Revenue_Flights'] > 0]

# 5. Calculate Waste Rate
model_waste['Reposition_Rate_%'] = (
    model_waste['Repositioning_Flights'] / 
    (model_waste['Revenue_Flights'] + model_waste['Repositioning_Flights']) * 100
)

# 6. Sort by most active models
model_waste = model_waste.sort_values(by='Revenue_Flights', ascending=False)

print("--- Wheels Up Efficiency: Revenue vs Waste (Q1 2026) ---")
print(model_waste.round(2))

--- Wheels Up Efficiency: Revenue vs Waste (Q1 2026) ---
                    Revenue_Flights  Repositioning_Flights  Reposition_Rate_%
aircraft_model
Phenom 300                     1823                    322              15.01
Citation X                     1121                    183              14.03
Hawker 400XP                   1048                    284              21.32
Citation CJ3                    714                    152              17.55
Challenger 300                  636                     83              11.54
400-XP                          398                     97              19.60
Citation CJ3+                   383                    102              21.03
Citation CJ4                    104                     18              14.75
GIV-SP                          103                     66              39.05
G550                             89                      9               9.18
GVII-G600                        82                     11              11.83
Phenom 300-E                     79                     11              12.22
Citation XLS+                    44                     12              21.43
G450                             40                      2               4.76
GVII-G500                        34                      6              15.00
Falcon 900EX-EASy                28                     16              36.36
Citation Excel                   24                     23              48.94
Learjet 60                       22                      9              29.03
Vision SF50-G2+                  20                      0               0.00
Citation Sovereign               12                      1               7.69
Citation M2                       6                      3              33.33
Citation XLS                      1                      0               0.00

/var/tmp/ipykernel_54433/1162103365.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  model_waste = wu_clean.groupby(['aircraft_model', 'reposition_flight']).size().unstack(fill_value=0)

In [21]:
# 1. Target Segments & Operator Types
target_segments = ['Light Jet', 'Super Light Jet']
target_operators = ['Branded Charter', 'Aircraft Management', 'Account Management']

# 2. Combined Filter: Revenue + Segments + Commercial Operators + No 'OTHER'
clean_commercial_df = df[
    (df['reposition_flight'] == 'N') & 
    (df['aircraft_segment'].isin(target_segments)) &
    (df['operator_type'].isin(target_operators)) &
    (~df['from_cluster'].str.contains('OTHER', case=False, na=False)) &
    (~df['to_cluster'].str.contains('OTHER', case=False, na=False))
].copy()

# 3. Build the Analysis Table
analysis_table = (
    clean_commercial_df.groupby('From_To_Cluster', observed=True)
    .agg(
        Total_Market_Flights=('From_To_Cluster', 'count'),
        WU_Flights=('is_wheels_up', 'sum')
    )
)

# 4. Calculate Share
analysis_table['WU_Share_%'] = (
    (analysis_table['WU_Flights'] / analysis_table['Total_Market_Flights']) * 100
).round(2)

# 5. Output the Top 20
top_20_commercial = analysis_table.sort_values(by='Total_Market_Flights', ascending=False).head(20)

print("--- Top 20 CLEAN Commercial Revenue Corridors (Charter & Management) ---")
print(top_20_commercial)

--- Top 20 CLEAN Commercial Revenue Corridors (Charter & Management) ---
                                         Total_Market_Flights  WU_Flights  \
From_To_Cluster
MIAMI_CLUSTER - ATLANTA_CLUSTER                          1264         181
ATLANTA_CLUSTER - MIAMI_CLUSTER                          1209         178
PARIS_CLUSTER - MILAN_CLUSTER                            1132           0
MILAN_CLUSTER - PARIS_CLUSTER                            1123           0
MILAN_CLUSTER - LONDON_CLUSTER                           1110           0
WASHINGTON_DC_CLUSTER - ATLANTA_CLUSTER                  1109         123
ATLANTA_CLUSTER - CHICAGO_CLUSTER                        1102         100
MIAMI_CLUSTER - CHICAGO_CLUSTER                          1095          71
LONDON_CLUSTER - MILAN_CLUSTER                           1077           0
CHICAGO_CLUSTER - ATLANTA_CLUSTER                        1077         116
MIAMI_CLUSTER - ORLANDO_CLUSTER                          1065         123
ATLANTA_CLUSTER - WASHINGTON_DC_CLUSTER                  1061         137
CHICAGO_CLUSTER - MIAMI_CLUSTER                          1053          70
ATLANTA_CLUSTER - ORLANDO_CLUSTER                        1049         167
ORLANDO_CLUSTER - ATLANTA_CLUSTER                        1039         168
ORLANDO_CLUSTER - MIAMI_CLUSTER                          1034         114
WASHINGTON_DC_CLUSTER - CHICAGO_CLUSTER                   908          61
HOUSTON_CLUSTER - DALLAS_CLUSTER                          883          40
CHICAGO_CLUSTER - WASHINGTON_DC_CLUSTER                   881          50
WASHINGTON_DC_CLUSTER - MIAMI_CLUSTER                     876          90

                                         WU_Share_%
From_To_Cluster
MIAMI_CLUSTER - ATLANTA_CLUSTER               14.32
ATLANTA_CLUSTER - MIAMI_CLUSTER               14.72
PARIS_CLUSTER - MILAN_CLUSTER                  0.00
MILAN_CLUSTER - PARIS_CLUSTER                  0.00
MILAN_CLUSTER - LONDON_CLUSTER                 0.00
WASHINGTON_DC_CLUSTER - ATLANTA_CLUSTER       11.09
ATLANTA_CLUSTER - CHICAGO_CLUSTER              9.07
MIAMI_CLUSTER - CHICAGO_CLUSTER                6.48
LONDON_CLUSTER - MILAN_CLUSTER                 0.00
CHICAGO_CLUSTER - ATLANTA_CLUSTER             10.77
MIAMI_CLUSTER - ORLANDO_CLUSTER               11.55
ATLANTA_CLUSTER - WASHINGTON_DC_CLUSTER       12.91
CHICAGO_CLUSTER - MIAMI_CLUSTER                6.65
ATLANTA_CLUSTER - ORLANDO_CLUSTER             15.92
ORLANDO_CLUSTER - ATLANTA_CLUSTER             16.17
ORLANDO_CLUSTER - MIAMI_CLUSTER               11.03
WASHINGTON_DC_CLUSTER - CHICAGO_CLUSTER        6.72
HOUSTON_CLUSTER - DALLAS_CLUSTER               4.53
CHICAGO_CLUSTER - WASHINGTON_DC_CLUSTER        5.68
WASHINGTON_DC_CLUSTER - MIAMI_CLUSTER         10.27

In [22]:
# 1. Filter for ONLY Wheels Up flights
wu_only = df[df['is_wheels_up'] == True].copy()

# 2. Filter that subset for anything including 'phenom'
wu_phenom_check = wu_only[wu_only['aircraft_model'].str.contains('phenom', case=False, na=False)]

# 3. Get unique combinations of Model and Segment for WU
wu_phenom_combinations = (
    wu_phenom_check.groupby(['aircraft_model', 'aircraft_segment'], observed=True)
    .size()
    .reset_index(name='Flight_Count')
    .sort_values(by='Flight_Count', ascending=False)
)

print("--- WHEELS UP ONLY: Phenom Classifications ---")
print(wu_phenom_combinations)

--- WHEELS UP ONLY: Phenom Classifications ---
  aircraft_model aircraft_segment  Flight_Count
0     Phenom 300        Light Jet          2145
1   Phenom 300-E        Light Jet            90

In [23]:
# 1. Filter for ONLY Wheels Up flights
wu_only = df[df['is_wheels_up'] == True].copy()

# 2. Filter that subset for anything including 'challenger' (case-insensitive)
wu_challenger_check = wu_only[wu_only['aircraft_model'].str.contains('challenger', case=False, na=False)]

# 3. Get unique combinations of Model and Segment for WU
wu_challenger_combinations = (
    wu_challenger_check.groupby(['aircraft_model', 'aircraft_segment'], observed=True)
    .size()
    .reset_index(name='Flight_Count')
    .sort_values(by='Flight_Count', ascending=False)
)

print("--- WHEELS UP ONLY: Challenger Classifications ---")
print(wu_challenger_combinations)

--- WHEELS UP ONLY: Challenger Classifications ---
   aircraft_model   aircraft_segment  Flight_Count
0  Challenger 300  Super Midsize Jet           719

In [24]:
# 1. Define the specific list of operators
    target_operators = [
        'Wheels Up Private Jets', 
        'Wheels Up LLC', 
        'Mountain Aviation', 
        'Alante Air Charter'
    ]

# 2. Filter the dataframe for these operators
specific_ops_df = df[df['Operator'].isin(target_operators)].copy()

# 3. Get counts and join with operator_type for a complete view
summary = (
    specific_ops_df.groupby('Operator')
    .agg(
        Flight_Count=('Operator', 'count'),
        Operator_Type=('operator_type', 'first')
    )
    .reset_index()
    .sort_values(by='Flight_Count', ascending=False)
)

# 4. Add a Total row for quick sanity checking
total_flights = summary['Flight_Count'].sum()
total_row = pd.DataFrame({
    'Operator': ['TOTAL CONSOLIDATED'], 
    'Flight_Count': [total_flights], 
    'Operator_Type': ['-']
})

consolidated_summary = pd.concat([summary, total_row], ignore_index=True)

print("--- Flight Counts for Specific WU Entities ---")

--- Flight Counts for Specific WU Entities ---
                     Operator  Flight_Count        Operator_Type
0      Wheels Up Private Jets          7572      Branded Charter
1          Alante Air Charter          1137  Aircraft Management
2           Mountain Aviation           530  Aircraft Management
3               Wheels Up LLC            20      Branded Charter
4             N900JT-Operator             0                  NaN
...                       ...           ...                  ...
14556         GAD Flights Ltd             0                  NaN
14557              GAT II LLC             0                  NaN
14558       GAZU Holdings Inc             0                  NaN
14559     G4 Investments Corp             0                  NaN
14560      TOTAL CONSOLIDATED          9259                    -

[14561 rows x 3 columns]

/var/tmp/ipykernel_54433/455654048.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  specific_ops_df.groupby('Operator')