# Light Jet Premium Extraction Audit — Phenom 300 Fleet

**Segment:** Light Jet &nbsp;|&nbsp; **Fleet:** Phenom 300 &nbsp;|&nbsp; 
**Data pipeline:** Strategic Rhombus — `final_wingx_24_25_lj` reference notebook

---

## Purpose

This notebook identifies the **highest-value pricing windows** across 20 LJ strategic corridors.
A corridor qualifies only when both signals are simultaneously present in the same time window:

| Criterion | Threshold | Meaning |
|---|---|---|
| Strong market demand | TOD velocity ≥ 15% | Window captures ≥ 15% of all corridor flights |
| Meaningful WUP presence | WUP share ≥ 2.0% | WUP holds a real position in that window |

The output is an actionable **Premium Extraction Matrix**: which corridors, which windows, and how hard to push on price.

---

## Data Sources

| File | Records | Coverage |
|---|---|---|
| `lj_dow_heatmaps.json` | 140 | 20 corridors × 7 days-of-week |
| `lj_tod_heatmaps.json` | 120 | 20 corridors × 6 time-of-day buckets |

Pre-computed corridor aggregates from the Strategic Rhombus pipeline.
Raw flight-level data is processed upstream — this notebook ingests summary records only.

---

## Column Glossary

| Column | Definition |
|---|---|
| `tod_market_velocity_pct` | % of corridor's annual flights occurring in this TOD window — measures market depth |
| `tod_wup_share_pct` | WUP flights ÷ total flights in that window — the core extraction signal |
| `dow_market_velocity_pct` | % of corridor's annual flights on this day-of-week |
| `dow_wup_share_pct` | WUP flights ÷ total flights on that day-of-week |

---

## Analysis Pipeline

| Cell | Output | Purpose |
|---|---|---|
| 1–3 | `df_dow_final`, `df_tod_final` | Load and normalize raw heatmap records |
| 4 | `df_best` (20 rows) | Rank-sum selection — one best DOW day + one best TOD slot per corridor |
| 5 | `df_categorized` (20 rows) | Premium extraction classification into 4 tiers |
| 6 | `df_value` (20 rows) | Revenue opportunity quantification per corridor |
| 7–8 | `df_signals` | Active corridors only (No Signal removed) |

In [1]:
# -----------------------------------------------------------------------------------------
# CELL 1: LOAD PRE-COMPUTED HEATMAP DATA
# Source: lj_dow_heatmaps.json  — 140 records (20 corridors x 7 DOW days)
#         lj_tod_heatmaps.json  — 120 records (20 corridors x 6 TOD slots)
# Derived from the Strategic Rhombus pipeline.
# -----------------------------------------------------------------------------------------
import pandas as pd
import numpy as np

df_dow = pd.read_json("lj_dow_heatmaps.json")
df_tod = pd.read_json("lj_tod_heatmaps.json")

print("Loading heatmap data...")
print(f"  DOW records : {len(df_dow['records']):,}")
print(f"  TOD records : {len(df_tod['records']):,}")

Loading heatmap data...
  DOW records : 140
  TOD records : 120

In [2]:
# -----------------------------------------------------------------------------------------
# CELL 2: NORMALIZE DOW RECORDS
# Output: df_dow_final — 140 rows
#         columns: corridor | dimension | dow_market_velocity_pct | dow_wup_share_pct
# -----------------------------------------------------------------------------------------
df_dow_final = pd.json_normalize(df_dow["records"])

print(f"DOW shape : {df_dow_final.shape}")
print(f"Corridors : {df_dow_final['corridor'].nunique()}")
print(f"Days      : {sorted(df_dow_final['dimension'].unique())}")
display(df_dow_final.head(7))

DOW shape : (140, 4)
Corridors : 20
Days      : ['Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']

,corridor,dimension,dow_market_velocity_pct,dow_wup_share_pct
0,South Florida ➔ New York City,Monday,17.0013,4.6338
1,South Florida ➔ New York City,Tuesday,14.3329,4.4326
2,South Florida ➔ New York City,Wednesday,13.1385,4.2553
3,South Florida ➔ New York City,Thursday,12.5540,4.6559
4,South Florida ➔ New York City,Friday,13.2147,2.6923
5,South Florida ➔ New York City,Saturday,11.6137,3.5011
6,South Florida ➔ New York City,Sunday,18.1449,2.6611

In [3]:
# -----------------------------------------------------------------------------------------
# CELL 3: NORMALIZE TOD RECORDS
# Output: df_tod_final — 120 rows
#         columns: corridor | dimension | tod_market_velocity_pct | tod_wup_share_pct
# -----------------------------------------------------------------------------------------
df_tod_final = pd.json_normalize(df_tod["records"])

print(f"TOD shape : {df_tod_final.shape}")
print(f"Corridors : {df_tod_final['corridor'].nunique()}")
print(f"Buckets   : {sorted(df_tod_final['dimension'].unique())}")
display(df_tod_final.head(6))

TOD shape : (120, 4)
Corridors : 20
Buckets   : ['07:00-09:59', '10:00-12:59', '13:00-15:59', '16:00-18:59', '19:00-21:59', 'Off-Peak (Late/Early)']

,corridor,dimension,tod_market_velocity_pct,tod_wup_share_pct
0,South Florida ➔ New York City,07:00-09:59,21.7535,4.5561
1,South Florida ➔ New York City,10:00-12:59,30.9022,3.7007
2,South Florida ➔ New York City,13:00-15:59,24.1169,4.5311
3,South Florida ➔ New York City,16:00-18:59,14.2313,3.3929
4,South Florida ➔ New York City,19:00-21:59,4.8793,2.0833
5,South Florida ➔ New York City,Off-Peak (Late/Early),4.1169,0.0000

## Data Structure After Normalization

Each JSON file contains one record per corridor-dimension pair.
Example TOD record:

    { "corridor": "DMV ➔ South Florida",
      "dimension": "10:00-12:59",
      "tod_market_velocity_pct": 31.30,
      "tod_wup_share_pct": 11.59 }

**Two critical properties of this data:**

1. **Velocity and WUP share are frequently anti-correlated on the same corridor.**
   The busiest time window is often *not* the one where WUP is most concentrated.
   A naive "pick the max velocity slot" approach would systematically select the wrong window.
   The rank-sum algorithm (Cell 4) resolves this by jointly optimizing both signals.

2. **`tod_wup_share_pct` is WUP's share *within the window*, not of total corridor volume.**
   A value of 11.59% on DMV → South Florida at 10:00–12:59 means roughly 1-in-9 flights
   in that slot is WUP — a very strong concentration.
   Summing velocity across all slots will exceed 100%; they are conditional shares, not a partition.

## Rank-Sum Dimension Selection — How It Works

For each corridor we pick **one DOW day** and **one TOD slot** where velocity and WUP share are simultaneously highest.
A simple "pick the max" approach fails because the fastest slot is rarely the one with the highest share.
Instead we use a **rank-sum**: rank each slot independently on both metrics, add the ranks, and pick the slot with the lowest total.

### Algorithm (applied separately to DOW and TOD)

1. For every slot in a corridor, assign `vel_rank` — rank **1 = fastest** (descending).
2. For every slot in a corridor, assign `wup_rank` — rank **1 = highest share** (descending).
3. `combined_rank = vel_rank + wup_rank`
4. Pick the slot with the **lowest** `combined_rank`.
5. Tiebreaker (equal `combined_rank`): highest `wup_share`, then highest `velocity`.

A slot that ranks #1 on both gets `combined_rank = 2` — the theoretical minimum with any number of slots.

---

### Hand-Trace Example — DMV → South Florida (TOD)

| Time Slot | tod_velocity | tod_wup | vel_rank | wup_rank | combined_rank |
|---|---|---|---|---|---|
| 07:00–09:59 | 21.1% | 9.3% | 3 | 4 | **7** |
| **10:00–12:59** | **31.3%** | **11.6%** | **1** | **1** | **2** ← winner |
| 13:00–15:59 | 24.5% | 10.1% | 2 | 2 | **4** |
| 16:00–18:59 | 15.3% | 9.4% | 4 | 3 | **7** |
| 19:00–21:59 | 4.9% | 6.4% | 5 | 5 | **10** |
| Off-Peak | 2.9% | 4.7% | 6 | 6 | **12** |

`10:00–12:59` ranks **#1 on velocity AND #1 on WUP share** → `combined_rank = 2` → selected.

---

### What the ranks protect against

| Scenario | Pure-velocity pick | Pure-wup pick | Rank-sum pick |
|---|---|---|---|
| Fastest slot has near-zero share | ✗ wrong slot | — | ✓ balanced |
| Best-share slot is off-peak (vel ≈ 2%) | — | ✗ wrong slot | ✓ balanced |
| Both metrics peak at same slot | ✓ correct | ✓ correct | ✓ correct |

**North Florida → Dallas edge case:** all 6 TOD slots have perfectly anti-correlated velocity and WUP
(fastest = lowest share). Every slot scores `combined_rank = 7`. Tiebreaker picks Off-Peak (highest wup = 2.63%),
which correctly lands in **No Signal** — no actionable premium window exists on this corridor.

In [4]:
# -----------------------------------------------------------------------------------------
# CELL 4: BEST DOW + TOD PER CORRIDOR — RANK-SUM SELECTION
# Logic  : vel_rank + wup_rank = combined_rank.  Lowest = closest to #1 on BOTH.
# Tiebreak: highest wup_share, then highest velocity.
# Output : df_best — 20 rows, one per corridor.
# -----------------------------------------------------------------------------------------

# ── DOW ─────────────────────────────────────────────────────────────────────
df_dow_ranked = df_dow_final.copy()
df_dow_ranked["vel_rank"] = (
    df_dow_ranked.groupby("corridor")["dow_market_velocity_pct"]
    .rank(ascending=False, method="min")
)
df_dow_ranked["wup_rank"] = (
    df_dow_ranked.groupby("corridor")["dow_wup_share_pct"]
    .rank(ascending=False, method="min")
)
df_dow_ranked["combined_rank"] = df_dow_ranked["vel_rank"] + df_dow_ranked["wup_rank"]

df_best_dow = (
    df_dow_ranked
    .sort_values(
        ["corridor", "combined_rank", "dow_wup_share_pct", "dow_market_velocity_pct"],
        ascending=[True, True, False, False]
    )
    .groupby("corridor", sort=True).first().reset_index()
    .rename(columns={
        "dimension":               "dow_dimension",
        "dow_market_velocity_pct": "dow_velocity_pct",
    })
    [["corridor", "dow_dimension", "dow_velocity_pct", "dow_wup_share_pct"]]
)

# ── TOD ─────────────────────────────────────────────────────────────────────
df_tod_ranked = df_tod_final.copy()
df_tod_ranked["vel_rank"] = (
    df_tod_ranked.groupby("corridor")["tod_market_velocity_pct"]
    .rank(ascending=False, method="min")
)
df_tod_ranked["wup_rank"] = (
    df_tod_ranked.groupby("corridor")["tod_wup_share_pct"]
    .rank(ascending=False, method="min")
)
df_tod_ranked["combined_rank"] = df_tod_ranked["vel_rank"] + df_tod_ranked["wup_rank"]

df_best_tod = (
    df_tod_ranked
    .sort_values(
        ["corridor", "combined_rank", "tod_wup_share_pct", "tod_market_velocity_pct"],
        ascending=[True, True, False, False]
    )
    .groupby("corridor", sort=True).first().reset_index()
    .rename(columns={
        "dimension":               "tod_dimension",
        "tod_market_velocity_pct": "tod_velocity_pct",
    })
    [["corridor", "tod_dimension", "tod_velocity_pct", "tod_wup_share_pct"]]
)

# ── Merge ────────────────────────────────────────────────────────────────────
df_best = (
    df_best_dow
    .merge(df_best_tod, on="corridor")
    [["corridor", "dow_dimension", "tod_dimension",
      "dow_velocity_pct", "tod_velocity_pct",
      "dow_wup_share_pct", "tod_wup_share_pct"]]
)

print(f"Best-dimension table: {df_best.shape}  (expect 20 x 7)")
display(df_best)

Best-dimension table: (20, 7)  (expect 20 x 7)

,corridor,dow_dimension,tod_dimension,dow_velocity_pct,tod_velocity_pct,dow_wup_share_pct,tod_wup_share_pct
0,Chicago ➔ Denver,Monday,10:00-12:59,14.5533,31.3305,3.2172,2.8643
1,Chicago ➔ South Florida,Friday,13:00-15:59,16.3783,23.1257,3.3451,3.9900
2,DMV ➔ South Florida,Friday,10:00-12:59,17.0175,31.3032,9.4737,11.5880
3,Dallas ➔ Denver,Friday,10:00-12:59,15.8143,35.9166,3.7313,3.0668
4,Dallas ➔ Phoenix Valley,Sunday,13:00-15:59,15.0358,29.5943,2.7778,3.4274
5,Dallas ➔ South Florida,Wednesday,10:00-12:59,16.2885,27.3828,3.0960,3.6832
6,Detroit ➔ South Florida,Saturday,10:00-12:59,14.0826,30.1376,9.4463,8.5236
7,Houston ➔ Denver,Tuesday,10:00-12:59,15.2464,41.2174,4.9430,4.3601
8,New York City ➔ South Florida,Thursday,07:00-09:59,16.3727,19.6367,3.3762,4.0214
9,North Florida ➔ Dallas,Sunday,Off-Peak (Late/Early),16.0457,2.2837,2.2472,2.6316
10,Pittsburgh ➔ South Florida,Saturday,13:00-15:59,12.6357,23.7907,7.8125,6.6390
11,South Florida ➔ Boston,Sunday,10:00-12:59,15.1149,34.4015,4.8000,4.2179
12,South Florida ➔ Chicago,Sunday,10:00-12:59,17.9860,31.2573,3.0744,3.3520
13,South Florida ➔ DMV,Wednesday,13:00-15:59,14.2641,22.8327,9.8940,11.4790
14,South Florida ➔ Dallas,Thursday,10:00-12:59,14.4144,31.4457,2.6786,1.9100
15,South Florida ➔ Detroit,Tuesday,10:00-12:59,14.4980,35.7497,8.3851,8.8161
16,South Florida ➔ New York City,Monday,07:00-09:59,17.0013,21.7535,4.6338,4.5561
17,South Florida ➔ Pittsburgh,Saturday,10:00-12:59,12.9767,30.1634,8.0153,4.7619
18,South Florida ➔ St. Louis,Wednesday,10:00-12:59,13.7115,31.6079,3.6145,3.3101
19,St. Louis ➔ South Florida,Monday,13:00-15:59,14.6284,23.8151,4.4000,3.9312

## Step 3 — Premium Extraction Classification

### Why TOD drives classification (not DOW)

The DOW winner identifies *which day* to target.
But pricing systems toggle premiums at the **time-of-day** level — not by individual calendar day.
`tod_wup_share_pct` is therefore the primary classification signal.

### Threshold derivation — data-driven, not arbitrary

All 20 corridor TOD winners were sorted by `tod_wup_share_pct` descending.
Cut points were placed at **natural distributional gaps**, not round numbers:

| Rank | Corridor | WUP% | Gap to next |
|---|---|---|---|
| 5 | Pittsburgh → South Florida | 6.64% | ↓ **1.88 pp gap** |
| 6 | South Florida → Pittsburgh | 4.76% | |
| 10 | New York City → South Florida | 4.02% | ↓ **0.03 pp gap** |
| 11 | Chicago → South Florida | 3.99% | |
| 15 | South Florida → Chicago | 3.35% | ↓ **0.04 pp gap** |
| 16 | South Florida → St. Louis | 3.31% | |

Cut points: **> 6.5%** (top tier), **≥ 4.0%** (second tier), **≥ 3.32%** (third tier).

### Category definitions

| Category | Condition | Revenue action |
|---|---|---|
| **Stronghold Extraction** | wup > 6.5% AND velocity > 15% | Maximum premium +25–30% — dominant presence, protect and maximize |
| **Surge Capture** | 4.0% ≤ wup ≤ 6.5% AND velocity > 15% | Aggressive push +20% — strong signal, room to grow share |
| **Niche Protection** | 3.32% ≤ wup < 4.0% | Moderate uplift +10–15% — defend share against competitive displacement |
| **Velocity Opportunity** | velocity > 25% AND 2.0% ≤ wup < 3.32% | Selective push +15–20% — high market activity, build WUP concentration |
| **No Signal** | all other | No pricing action — insufficient evidence for extraction |

### Dual-criterion quality gate

Every active candidate satisfies **both** criteria:
- ✅ Strong market demand: velocity ≥ 15% (or ≥ 25% for Velocity Opportunity)
- ✅ Meaningful WUP presence: wup ≥ 2.0% across all categories (no sub-2% extractions)

18 of 20 corridors produce a `combined_rank = 2` winner — meaning the selected TOD slot
ranks #1 on **both** velocity and WUP simultaneously. The remaining 2 are explained in the rank-sum section.

In [5]:
# -----------------------------------------------------------------------------------------
# CELL 5: PREMIUM EXTRACTION CATEGORIES (TOD-DRIVEN)
#
# Stronghold Extraction  (+30%)   tod_wup > 6.5%     AND tod_velocity > 15%
# Surge Capture          (+20%)   tod_wup 4.0-6.5%   AND tod_velocity > 15%
# Niche Protection       (+10%)   tod_wup 3.32-4.0%
# Velocity Opportunity   (+15/20%) tod_velocity > 25% AND tod_wup 2.0-3.32%
# No Signal                       low velocity AND low wup
# -----------------------------------------------------------------------------------------

conditions = [
    (df_best["tod_wup_share_pct"] > 6.5)   & (df_best["tod_velocity_pct"] > 15),
    (df_best["tod_wup_share_pct"] >= 4.0)  & (df_best["tod_wup_share_pct"] <= 6.5) & (df_best["tod_velocity_pct"] > 15),
    (df_best["tod_wup_share_pct"] >= 3.32) & (df_best["tod_wup_share_pct"] <  4.0),
    (df_best["tod_velocity_pct"]  > 25)    & (df_best["tod_wup_share_pct"] >= 2.0) & (df_best["tod_wup_share_pct"] <  3.32),
]
labels = ["Stronghold Extraction", "Surge Capture", "Niche Protection", "Velocity Opportunity"]

df_categorized = df_best.copy()
df_categorized["category"] = np.select(conditions, labels, default="No Signal")

df_categorized = df_categorized[[
    "corridor",
    "dow_dimension", "dow_velocity_pct", "dow_wup_share_pct",
    "tod_dimension", "tod_velocity_pct", "tod_wup_share_pct",
    "category",
]]

category_order = ["Stronghold Extraction", "Surge Capture", "Niche Protection", "Velocity Opportunity", "No Signal"]
df_categorized["category"] = pd.Categorical(df_categorized["category"], categories=category_order, ordered=True)
df_categorized = (
    df_categorized
    .sort_values(["category", "tod_velocity_pct", "tod_wup_share_pct"], ascending=[True, False, False])
    .reset_index(drop=True)
)

print("PREMIUM EXTRACTION CATEGORY DISTRIBUTION")
print("-" * 42)
print(df_categorized["category"].value_counts().reindex(category_order).to_string())
print()
display(df_categorized)

PREMIUM EXTRACTION CATEGORY DISTRIBUTION
------------------------------------------
category
Stronghold Extraction    5
Surge Capture            5
Niche Protection         5
Velocity Opportunity     3
No Signal                2

,corridor,dow_dimension,dow_velocity_pct,dow_wup_share_pct,tod_dimension,tod_velocity_pct,tod_wup_share_pct,category
0,South Florida ➔ Detroit,Tuesday,14.4980,8.3851,10:00-12:59,35.7497,8.8161,Stronghold Extraction
1,DMV ➔ South Florida,Friday,17.0175,9.4737,10:00-12:59,31.3032,11.5880,Stronghold Extraction
2,Detroit ➔ South Florida,Saturday,14.0826,9.4463,10:00-12:59,30.1376,8.5236,Stronghold Extraction
3,Pittsburgh ➔ South Florida,Saturday,12.6357,7.8125,13:00-15:59,23.7907,6.6390,Stronghold Extraction
4,South Florida ➔ DMV,Wednesday,14.2641,9.8940,13:00-15:59,22.8327,11.4790,Stronghold Extraction
5,Houston ➔ Denver,Tuesday,15.2464,4.9430,10:00-12:59,41.2174,4.3601,Surge Capture
6,South Florida ➔ Boston,Sunday,15.1149,4.8000,10:00-12:59,34.4015,4.2179,Surge Capture
7,South Florida ➔ Pittsburgh,Saturday,12.9767,8.0153,10:00-12:59,30.1634,4.7619,Surge Capture
8,South Florida ➔ New York City,Monday,17.0013,4.6338,07:00-09:59,21.7535,4.5561,Surge Capture
9,New York City ➔ South Florida,Thursday,16.3727,3.3762,07:00-09:59,19.6367,4.0214,Surge Capture
10,South Florida ➔ Chicago,Sunday,17.9860,3.0744,10:00-12:59,31.2573,3.3520,Niche Protection
11,Dallas ➔ Phoenix Valley,Sunday,15.0358,2.7778,13:00-15:59,29.5943,3.4274,Niche Protection
12,Dallas ➔ South Florida,Wednesday,16.2885,3.0960,10:00-12:59,27.3828,3.6832,Niche Protection
13,St. Louis ➔ South Florida,Monday,14.6284,4.4000,13:00-15:59,23.8151,3.9312,Niche Protection
14,Chicago ➔ South Florida,Friday,16.3783,3.3451,13:00-15:59,23.1257,3.9900,Niche Protection
15,Dallas ➔ Denver,Friday,15.8143,3.7313,10:00-12:59,35.9166,3.0668,Velocity Opportunity
16,South Florida ➔ St. Louis,Wednesday,13.7115,3.6145,10:00-12:59,31.6079,3.3101,Velocity Opportunity
17,Chicago ➔ Denver,Monday,14.5533,3.2172,10:00-12:59,31.3305,2.8643,Velocity Opportunity
18,South Florida ➔ Dallas,Thursday,14.4144,2.6786,10:00-12:59,31.4457,1.9100,No Signal
19,North Florida ➔ Dallas,Sunday,16.0457,2.2472,Off-Peak (Late/Early),2.2837,2.6316,No Signal

## Step 4 — Revenue Opportunity Quantification

### Fleet parameters (Q1 Phenom 300)

| Parameter | Low Scenario | High Scenario |
|---|---|---|
| Fleet hours (Q1) | 3,400 hrs | 6,800 hrs |
| Active tails | 20 | 40 |
| Hourly rate | $9,500 | $9,500 |
| Corridor allocation | 20 corridors | 20 corridors |

---

### SLI — Surge Loyalty Index

> **SLI = `tod_wup_share_pct` / `NATIONAL_BASELINE`**
> where `NATIONAL_BASELINE = 4.0%` (overall WUP Light Jet long-haul market share, from reference notebook Cell 5)

SLI measures how over- or under-indexed WUP is in the corridor's peak window **relative to the national average**:
- **SLI = 1.0** → WUP presence equals the national average in that window
- **SLI = 2.9** → WUP is 2.9× the national average (e.g. DMV → South Florida, 10:00–12:59)
- **SLI < 1.0** → WUP is underweight; below market average in that window

---

### Hours-in-Window Formula

> **`hours = (Fleet_hrs / N_corridors) × (tod_velocity_pct / 100) × SLI`**

Step-by-step:

| Factor | What it does |
|---|---|
| `Fleet_hrs / N_corridors` | Pro-rata fleet allocation per corridor (170 hrs/corridor at low, 340 at high) |
| `× tod_velocity_pct / 100` | Scales to the fraction of those hours in the peak TOD window |
| `× SLI` | Adjusts for WUP's concentration — overweight corridors capture more revenue-eligible hours |

---

### Variable Toggle — Pricing Uplift within Category

The toggle is **not flat** within a category. It responds to signal strength:

| Category | Condition for high toggle | High | Low |
|---|---|---|---|
| Stronghold Extraction | SLI > 2.0 (more than 2× national avg) | +30% | +25% |
| Surge Capture | — | +20% | +20% |
| Niche Protection | wup > 3.6% | +15% | +10% |
| Velocity Opportunity | velocity > 33% | +20% | +15% |

Corridors with stronger signals within their tier receive the higher toggle — ensuring the pricing lever
is proportional to conviction, not just category membership.

---

### Value Formula

> **`value = hours_in_window × hourly_rate × toggle_pct`**

This is the **incremental revenue** from applying the pricing uplift during the peak extraction window.
The model assumes the toggle is applied to WUP-bookable capacity — the SLI multiplier ensures
we are only sizing the opportunity proportional to WUP's actual presence.

In [6]:
# -----------------------------------------------------------------------------------------
# CELL 6: VALUE CREATION TABLE
#
# Phenom Base (Q1) : Low  = 3,400 hrs (20 tails)  |  High = 6,800 hrs (40 tails)
# Phenom share     : ~46% of total WUP Light Jet activity
# Hourly rate      : $9,500
# SLI              : tod_wup_share_pct / NATIONAL_BASELINE
#                    NATIONAL_BASELINE = 4.0% (overall WUP LJ share, ref Cell 5 source nb)
# Hours in window  : (Phenom hrs / N corridors) x tod_velocity_pct x SLI
#
# Toggle (variable within each category, driven by SLI / wup / velocity):
#   Stronghold  SLI > 2.0  -> +30%   else +25%
#   Surge                  -> +20%
#   Niche       wup > 3.6% -> +15%   else +10%
#   Vel Opp     vel > 33%  -> +20%   else +15%
# -----------------------------------------------------------------------------------------

PHENOM_LOW        = 3_400
PHENOM_HIGH       = 6_800
N_CORRIDORS       = 20
HOURLY_RATE       = 9_500
NATIONAL_BASELINE = 4.0

def _get_toggle(cat, wup, vel):
    sli = wup / 4.0
    if   cat == 'Stronghold Extraction': return 0.30 if sli  >  2.0 else 0.25
    elif cat == 'Surge Capture':         return 0.20
    elif cat == 'Niche Protection':      return 0.15 if wup  >  3.6 else 0.10
    elif cat == 'Velocity Opportunity':  return 0.20 if vel  > 33.0 else 0.15
    else:                                return 0.00

df_value = df_categorized.copy()
df_value["sli"]        = (df_value["tod_wup_share_pct"] / NATIONAL_BASELINE).round(2)
df_value["toggle_pct"] = df_value.apply(
    lambda r: _get_toggle(str(r["category"]), r["tod_wup_share_pct"], r["tod_velocity_pct"]),
    axis=1
)

df_value["hours_low"]  = ((PHENOM_LOW  / N_CORRIDORS) * (df_value["tod_velocity_pct"] / 100) * df_value["sli"]).round(1)
df_value["hours_high"] = ((PHENOM_HIGH / N_CORRIDORS) * (df_value["tod_velocity_pct"] / 100) * df_value["sli"]).round(1)

df_value["value_low"]  = (df_value["hours_low"]  * HOURLY_RATE * df_value["toggle_pct"]).round(0).astype(int)
df_value["value_high"] = (df_value["hours_high"] * HOURLY_RATE * df_value["toggle_pct"]).round(0).astype(int)

df_value = df_value[[
    "corridor", "category",
    "tod_dimension", "tod_velocity_pct", "tod_wup_share_pct",
    "sli", "toggle_pct",
    "hours_low", "hours_high",
    "value_low", "value_high",
]]

summary = (
    df_value.groupby("category", observed=True)[["value_low", "value_high"]]
    .sum()
    .assign(
        value_low  = lambda d: d["value_low"].map("${:,.0f}".format),
        value_high = lambda d: d["value_high"].map("${:,.0f}".format),
    )
)
print("VALUE BY CATEGORY (Q1 Phenom Fleet)")
print("-" * 42)
display(summary)
print()

df_value["value_low"]  = df_value["value_low"].map("${:,.0f}".format)
df_value["value_high"] = df_value["value_high"].map("${:,.0f}".format)
display(df_value)

VALUE BY CATEGORY (Q1 Phenom Fleet)
------------------------------------------

                        value_low  value_high
category
Stronghold Extraction  $1,608,587  $3,217,697
Surge Capture            $521,930  $1,043,670
Niche Protection         $257,069    $514,282
Velocity Opportunity     $207,433    $415,008
No Signal                      $0          $0

,corridor,category,tod_dimension,tod_velocity_pct,tod_wup_share_pct,sli,toggle_pct,hours_low,hours_high,value_low,value_high
0,South Florida ➔ Detroit,Stronghold Extraction,10:00-12:59,35.7497,8.8161,2.20,0.30,133.7,267.4,"$381,045","$762,090"
1,DMV ➔ South Florida,Stronghold Extraction,10:00-12:59,31.3032,11.5880,2.90,0.30,154.3,308.6,"$439,755","$879,510"
2,Detroit ➔ South Florida,Stronghold Extraction,10:00-12:59,30.1376,8.5236,2.13,0.30,109.1,218.3,"$310,935","$622,155"
3,Pittsburgh ➔ South Florida,Stronghold Extraction,13:00-15:59,23.7907,6.6390,1.66,0.25,67.1,134.3,"$159,362","$318,962"
4,South Florida ➔ DMV,Stronghold Extraction,13:00-15:59,22.8327,11.4790,2.87,0.30,111.4,222.8,"$317,490","$634,980"
5,Houston ➔ Denver,Surge Capture,10:00-12:59,41.2174,4.3601,1.09,0.20,76.4,152.8,"$145,160","$290,320"
6,South Florida ➔ Boston,Surge Capture,10:00-12:59,34.4015,4.2179,1.05,0.20,61.4,122.8,"$116,660","$233,320"
7,South Florida ➔ Pittsburgh,Surge Capture,10:00-12:59,30.1634,4.7619,1.19,0.20,61.0,122.0,"$115,900","$231,800"
8,South Florida ➔ New York City,Surge Capture,07:00-09:59,21.7535,4.5561,1.14,0.20,42.2,84.3,"$80,180","$160,170"
9,New York City ➔ South Florida,Surge Capture,07:00-09:59,19.6367,4.0214,1.01,0.20,33.7,67.4,"$64,030","$128,060"
10,South Florida ➔ Chicago,Niche Protection,10:00-12:59,31.2573,3.3520,0.84,0.10,44.6,89.3,"$42,370","$84,835"
11,Dallas ➔ Phoenix Valley,Niche Protection,13:00-15:59,29.5943,3.4274,0.86,0.10,43.3,86.5,"$41,135","$82,175"
12,Dallas ➔ South Florida,Niche Protection,10:00-12:59,27.3828,3.6832,0.92,0.15,42.8,85.7,"$60,990","$122,122"
13,St. Louis ➔ South Florida,Niche Protection,13:00-15:59,23.8151,3.9312,0.98,0.15,39.7,79.4,"$56,572","$113,145"
14,Chicago ➔ South Florida,Niche Protection,13:00-15:59,23.1257,3.9900,1.00,0.15,39.3,78.6,"$56,002","$112,005"
15,Dallas ➔ Denver,Velocity Opportunity,10:00-12:59,35.9166,3.0668,0.77,0.20,47.0,94.0,"$89,300","$178,600"
16,South Florida ➔ St. Louis,Velocity Opportunity,10:00-12:59,31.6079,3.3101,0.83,0.15,44.6,89.2,"$63,555","$127,110"
17,Chicago ➔ Denver,Velocity Opportunity,10:00-12:59,31.3305,2.8643,0.72,0.15,38.3,76.7,"$54,578","$109,298"
18,South Florida ➔ Dallas,No Signal,10:00-12:59,31.4457,1.9100,0.48,0.00,25.7,51.3,$0,$0
19,North Florida ➔ Dallas,No Signal,Off-Peak (Late/Early),2.2837,2.6316,0.66,0.00,2.6,5.1,$0,$0

In [7]:
# -----------------------------------------------------------------------------------------
# CELL 7: ACTIVE CORRIDORS (EXCLUDE NO SIGNAL)
# Output: df_signals — corridors with an actionable premium category.
# -----------------------------------------------------------------------------------------

df_signals = (
    df_value[df_value["category"].astype(str) != "No Signal"]
    .reset_index(drop=True)
)

print(f"Active corridors : {len(df_signals)} / {len(df_value)}")
display(df_signals)

Active corridors : 18 / 20

,corridor,category,tod_dimension,tod_velocity_pct,tod_wup_share_pct,sli,toggle_pct,hours_low,hours_high,value_low,value_high
0,South Florida ➔ Detroit,Stronghold Extraction,10:00-12:59,35.7497,8.8161,2.20,0.30,133.7,267.4,"$381,045","$762,090"
1,DMV ➔ South Florida,Stronghold Extraction,10:00-12:59,31.3032,11.5880,2.90,0.30,154.3,308.6,"$439,755","$879,510"
2,Detroit ➔ South Florida,Stronghold Extraction,10:00-12:59,30.1376,8.5236,2.13,0.30,109.1,218.3,"$310,935","$622,155"
3,Pittsburgh ➔ South Florida,Stronghold Extraction,13:00-15:59,23.7907,6.6390,1.66,0.25,67.1,134.3,"$159,362","$318,962"
4,South Florida ➔ DMV,Stronghold Extraction,13:00-15:59,22.8327,11.4790,2.87,0.30,111.4,222.8,"$317,490","$634,980"
5,Houston ➔ Denver,Surge Capture,10:00-12:59,41.2174,4.3601,1.09,0.20,76.4,152.8,"$145,160","$290,320"
6,South Florida ➔ Boston,Surge Capture,10:00-12:59,34.4015,4.2179,1.05,0.20,61.4,122.8,"$116,660","$233,320"
7,South Florida ➔ Pittsburgh,Surge Capture,10:00-12:59,30.1634,4.7619,1.19,0.20,61.0,122.0,"$115,900","$231,800"
8,South Florida ➔ New York City,Surge Capture,07:00-09:59,21.7535,4.5561,1.14,0.20,42.2,84.3,"$80,180","$160,170"
9,New York City ➔ South Florida,Surge Capture,07:00-09:59,19.6367,4.0214,1.01,0.20,33.7,67.4,"$64,030","$128,060"
10,South Florida ➔ Chicago,Niche Protection,10:00-12:59,31.2573,3.3520,0.84,0.10,44.6,89.3,"$42,370","$84,835"
11,Dallas ➔ Phoenix Valley,Niche Protection,13:00-15:59,29.5943,3.4274,0.86,0.10,43.3,86.5,"$41,135","$82,175"
12,Dallas ➔ South Florida,Niche Protection,10:00-12:59,27.3828,3.6832,0.92,0.15,42.8,85.7,"$60,990","$122,122"
13,St. Louis ➔ South Florida,Niche Protection,13:00-15:59,23.8151,3.9312,0.98,0.15,39.7,79.4,"$56,572","$113,145"
14,Chicago ➔ South Florida,Niche Protection,13:00-15:59,23.1257,3.9900,1.00,0.15,39.3,78.6,"$56,002","$112,005"
15,Dallas ➔ Denver,Velocity Opportunity,10:00-12:59,35.9166,3.0668,0.77,0.20,47.0,94.0,"$89,300","$178,600"
16,South Florida ➔ St. Louis,Velocity Opportunity,10:00-12:59,31.6079,3.3101,0.83,0.15,44.6,89.2,"$63,555","$127,110"
17,Chicago ➔ Denver,Velocity Opportunity,10:00-12:59,31.3305,2.8643,0.72,0.15,38.3,76.7,"$54,578","$109,298"

In [8]:
# ─────────────────────────────────────────────────────────────────────────────
# CELL 8: PREMIUM EXTRACTION — FORMATTED CATEGORY TABLES
# Styled HTML output per category matching operational report format.
# ─────────────────────────────────────────────────────────────────────────────

from IPython.display import HTML

abbrev_map = {
    'South Florida':  'S. Fla',
    'New York City':  'NYC',
    'North Florida':  'N. Fla',
    'Pittsburgh':     'Pitt',
    'Phoenix Valley': 'Phoenix',
}

def shorten(corridor):
    parts = corridor.split(' ➔ ')
    return ' → '.join(abbrev_map.get(p, p) for p in parts)

category_meta = {
    'Stronghold Extraction': 'HIGH-CONVICTION CORRIDOR PAIRS',
    'Surge Capture':         'MOMENTUM CORRIDOR PAIRS',
    'Niche Protection':      'LOWER-INTENSITY CORRIDOR PAIRS',
    'Velocity Opportunity':  'HIGH-DEMAND UNDERWEIGHT PAIRS',
}

# Rebuild numeric values using the same variable toggle logic
def _get_toggle(cat, wup, vel):
    sli = wup / 4.0
    if   cat == 'Stronghold Extraction': return 0.30 if sli  >  2.0 else 0.25
    elif cat == 'Surge Capture':         return 0.20
    elif cat == 'Niche Protection':      return 0.15 if wup  >  3.6 else 0.10
    elif cat == 'Velocity Opportunity':  return 0.20 if vel  > 33.0 else 0.15
    else:                                return 0.00

_df = df_categorized.copy()
_df['toggle_pct'] = _df.apply(
    lambda r: _get_toggle(str(r['category']), r['tod_wup_share_pct'], r['tod_velocity_pct']),
    axis=1
)
_df['sli']      = _df['tod_wup_share_pct'] / 4.0
_df['val_low']  = (3400 / 20) * (_df['tod_velocity_pct'] / 100) * _df['sli'] * 9500 * _df['toggle_pct']
_df['val_high'] = (6800 / 20) * (_df['tod_velocity_pct'] / 100) * _df['sli'] * 9500 * _df['toggle_pct']
_active = _df[_df['category'].astype(str) != 'No Signal'].reset_index(drop=True)

CSS = """
<style>
.pex-wrap { font-family: 'Segoe UI', Arial, sans-serif; max-width: 860px; margin-bottom: 40px; }
.pex-meta { font-size: 11px; font-weight: 700; letter-spacing: 1.5px; color: #0055cc; margin-bottom: 6px; }
.pex-title { font-size: 26px; font-weight: 800; color: #0d1b3e;
             border-left: 5px solid #0055cc; padding-left: 12px; margin: 0 0 14px 0; }
.pex-table { width: 100%; border-collapse: collapse; font-size: 13px; }
.pex-table thead tr { background: #0d1b3e; color: #fff; }
.pex-table thead th { padding: 9px 12px; text-align: left; font-weight: 600; }
.pex-table thead th.right { text-align: right; }
.pex-table tbody tr { border-bottom: 1px solid #e8e8e8; }
.pex-table tbody tr:hover { background: #f5f8ff; }
.pex-table td { padding: 10px 12px; vertical-align: top; }
.pex-table td.num { color: #0055cc; font-weight: 700; width: 32px; }
.pex-table td.right { text-align: right; font-variant-numeric: tabular-nums; }
.pex-table td.toggle-hi  { color: #1a7a1a; font-weight: 700; }
.pex-table td.toggle-lo  { color: #b35c00; font-weight: 700; }
.pex-table tfoot tr { background: #f0f0f0; font-weight: 700; }
.pex-table tfoot td { padding: 9px 12px; }
.pex-table tfoot td.right { text-align: right; }
.pex-spacer { height: 36px; }
</style>
"""

def toggle_label(pct):
    return f"+{int(round(pct*100))}%"

def toggle_class(pct, hi_thresh):
    return 'toggle-hi' if pct >= hi_thresh else 'toggle-lo'

hi_thresh = {
    'Stronghold Extraction': 0.30,
    'Surge Capture':         0.20,
    'Niche Protection':      0.15,
    'Velocity Opportunity':  0.20,
}

def build_table(cat_name, df_cat, row_start):
    subtitle = category_meta[cat_name]
    ht = hi_thresh[cat_name]
    sub_low  = df_cat['val_low'].sum()
    sub_high = df_cat['val_high'].sum()

    rows_html = ''
    for i, (_, r) in enumerate(df_cat.iterrows()):
        tc = toggle_class(r['toggle_pct'], ht)
        rows_html += f"""
        <tr>
          <td class="num">{row_start + i}</td>
          <td>{shorten(r['corridor'])}</td>
          <td>
            <div style="font-weight:700;color:#0d1b3e">{r['dow_dimension']}</div>
            <div style="font-size:11px;color:#666">{r['tod_dimension']}</div>
          </td>
          <td>{r['tod_wup_share_pct']:.1f}%</td>
          <td class="{tc}">{toggle_label(r['toggle_pct'])}</td>
          <td class="right">${r['val_low']:,.0f}</td>
          <td class="right">${r['val_high']:,.0f}</td>
        </tr>"""

    return f"""
<div class="pex-wrap">
  <div class="pex-meta">PHENOM 300 &nbsp;|&nbsp; {cat_name.upper()} &nbsp;|&nbsp; {subtitle}</div>
  <h2 class="pex-title">{cat_name} Toggles</h2>
  <table class="pex-table">
    <thead>
      <tr>
        <th>#</th><th>Corridor / Pair</th><th>Operational Detail</th>
        <th>Intensity</th><th>Toggle</th>
        <th class="right">Q1 Low (20T)</th><th class="right">Q1 High (40T)</th>
      </tr>
    </thead>
    <tbody>{rows_html}</tbody>
    <tfoot>
      <tr>
        <td colspan="5">SUBTOTAL</td>
        <td class="right">${sub_low:,.0f}</td>
        <td class="right">${sub_high:,.0f}</td>
      </tr>
    </tfoot>
  </table>
</div>
<div class="pex-spacer"></div>"""

html_out = CSS
row_num = 1
for cat in ['Stronghold Extraction', 'Surge Capture', 'Niche Protection', 'Velocity Opportunity']:
    df_cat = _active[_active['category'].astype(str) == cat]
    if df_cat.empty:
        continue
    html_out += build_table(cat, df_cat, row_num)
    row_num += len(df_cat)

grand_low  = _active['val_low'].sum()
grand_high = _active['val_high'].sum()
html_out += f"""
<div class="pex-wrap">
  <table class="pex-table">
    <tfoot>
      <tr>
        <td colspan="5" style="font-size:15px;">GRAND TOTAL (Q1 Phenom Fleet)</td>
        <td class="right" style="font-size:15px;">${grand_low:,.0f}</td>
        <td class="right" style="font-size:15px;">${grand_high:,.0f}</td>
      </tr>
    </tfoot>
  </table>
</div>"""

display(HTML(html_out))

---

## Results Interpretation Guide

### Priority order for revenue management action

| Priority | Category | Action |
|---|---|---|
| 1 | **Stronghold Extraction** | Implement maximum toggles immediately — high conviction, high share |
| 2 | **Surge Capture** | Deploy within the week — strong signal, competitive windows |
| 3 | **Niche Protection** | Schedule for next cycle — moderate, protect before competition moves |
| 4 | **Velocity Opportunity** | Monitor and test — demand is real but WUP share is still building |

### Reading the SLI column

SLI is the clearest single indicator of how well-positioned WUP is in a corridor-window pair.
Any SLI > 1.5 represents a meaningfully above-average WUP concentration — a reliable extraction signal.
SLI > 2.0 (Stronghold threshold) represents a dominant WUP position that should be monetized aggressively.

### Low vs High scenario

The low/high range reflects Q1 fleet deployment uncertainty (20 vs 40 tails).
Both scenarios use identical toggle logic — the range scales linearly with fleet hours.
Use low as a floor for planning; high as upside for investment cases.